#!/bin/sh

### BEGIN INIT INFO
# Provides:          wifiSearcher
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
PID_FILE="PID_WIFISEARCHER"
WORKDIR="/home/pi/Documents/uCode/hiberus"

case $1 in
	start)
		echo "Starting server"
		cd $WORKDIR
		python3 -m server &
		echo $! > $PID_FILE
	;;
	stop)
		echo "Stopping server"
		cd $WORKDIR
		kill $(cat $PID_FILE)
	;;
	*)
		echo "Usage: wifiSearcher {start|stop}"
		exit 1
	;;
esac

exit 0
