#!/bin/sh

### BEGIN INIT INFO
# Provides:          wifiSearcher
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case $1 in
	start)
	echo "Starting"
	cd /home/pi/Documents/uCode/hiberus
	python3 -m server wlan0 &
	;;
	stop)
	echo "Stoping"
	killall python3
	;;
	*)
	echo "Usage: /etc/init.d/wifiSearcher {start|stop}"
	exit 1
	;;
esac

exit 0

